"""Add upload_date column to File model with default

Revision ID: e04dce66c637
Revises: fe6fea7700d4
Create Date: 2025-05-26 21:42:09.036772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04dce66c637'
down_revision = 'fe6fea7700d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('s3_key')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_key', sa.VARCHAR(length=512), nullable=True))
        batch_op.alter_column('upload_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
